# Generated by Django 4.2 on 2023-04-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Answer ', 'verbose_name_plural': 'Answers '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test ', 'verbose_name_plural': 'Tests '},
        ),
        migrations.AlterModelTable(
            name='answers',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
    ]
