# Generated by Django 4.2 on 2023-04-13 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_answers_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(help_text='Upload test file', upload_to='testfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Test File'),
        ),
    ]
