# Generated by Django 4.1.7 on 2023-04-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_test_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('telegram_id', models.CharField(max_length=20, unique=True, verbose_name='Telegram ID')),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='myapp.category', verbose_name='Category'),
        ),
    ]
