# Generated by Django 4.1.7 on 2023-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_botuser_alter_answers_test_alter_test_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=150, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('test_code', models.CharField(max_length=150, verbose_name='Test Code')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
