# Generated by Django 4.1.7 on 2023-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_testdone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdone',
            options={'verbose_name': 'Test User', 'verbose_name_plural': 'Test Users'},
        ),
    ]
