# Generated by Django 4.1.7 on 2023-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_testdone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdone',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
