# Generated by Django 4.1.7 on 2023-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_testdone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdone',
            name='false_answers',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='False Answers'),
        ),
        migrations.AddField(
            model_name='testdone',
            name='true_answers',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='True Answers'),
        ),
    ]
